site_name: FastAPI-Tags
site_url: https://pydanny.github.io/fastapi-tags/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_if_no_docstring: true
            heading_level: 2

nav:
  - Home: index.md
  - API Reference:
    - Core: api/core.md
    - HTML Tags: api/tags.md
    - SVG Tags: api/svg.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true